### ISSUE TITLE
Spring Cloud Gateway - 网关动态路由

### ISSUE THREAD

**Issue by TFdream** [TFdream/spring-cloud-tutorials#21]
## 动态路由背景
在使用 Cloud Gateway 的时候，官方文档提供的方案总是基于配置文件配置的方式

例如：
```
spring:
      routes:
        - id: auth
          uri: ${gateway.route.url.uaa-service}
          predicates:
            - Path=/api-uaa/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: auth-login-page
          uri: ${gateway.route.url.uaa-service}
          predicates:
            - Path=/login.html
          filters:
            - PreserveHostHeader
```

配置更改需要重启服务，不能满足实际生产过程中的动态刷新、实时变更的业务需求。
