### ISSUE TITLE
SpringCloud教程 - 服务间调用

### ISSUE THREAD

**Issue by TFdream** [TFdream/spring-cloud-tutorials#3]
在上一篇我们介绍了SpringCloud中的注册中心组件Eureka。Eureka的作用是做服务注册与发现的，目的是让不同的服务与服务之间都可以通过注册中心进行间接关联，并且可以通过注册中心有效的管理不同服务与服务的运行状态。但在微服务的架构中，服务与服务只知道对方的服务地址是没有用的，它们的本质还是需要彼此进行通信的，这也是微服务最核心的功能之一。

在SpringCloud中为了解决服务与服务调用的问题，于是提供了两种方式来进行调用。也就是RestTemplate和Feign。虽然从名字上看这两种调用的方式不同，但在底层还是和HttpClient一样，采用http的方式进行调用的。只不过是对HttpClient进行的封装。下面我们来详细的介绍一下这两种方式的区别，我们首先看一下RestTemplate的方式。

## 方式一：RestTemplate + LoadBalancerClient
先看一下 看一下server端application.yml配置:
```
# 服务端口号
server:
  port: 8080

# 服务名称
spring:
  application:
    name: spring-cloud-consul-provider
  cloud:
    consul:
      host: http://localhost/
      port: 80
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        prefer-ip-address: true
        heartbeat:
          enabled: true
```
为了演示我们服务间的调用，所以我们需要创建一个Controller,并编写一个简单的接口来供client调用。
```

/**
 * 服务端接口
 * @author Ricky Fung
 */
@RestController
@RequestMapping("/api/server")
public class UserController {
    private final Logger LOG = LoggerFactory.getLogger(this.getClass());

    @GetMapping("/users")
    public List<UserDTO> list() {
        LOG.info("查询用户列表开始");
        List<UserDTO> userList = new ArrayList<>();
        for (int i=0; i<5; i++) {
            UserDTO userDTO = new UserDTO();
            userDTO.setId(SeqUtils.nextId());
            userDTO.setName("张三丰"+i);
            userList.add(userDTO);
        }
        return userList;
    }
}

```

因为注册中心知道所有服务的地址，这样我们通过注册中心就可以知道server端的接口地址，这样就避免了server端服务更改时，要同步更改client代码了。

```
@Service
public class UserService {
    private final Logger LOG = LoggerFactory.getLogger(this.getClass());

    @Resource
    private LoadBalancerClient loadBalancerClient;

    @Resource
    private RestTemplate defaultRestTemplate;

    /**
     * 方式一：LoadBalancerClient + RestTemplate
     * @return
     */
    public String getUserList1() {
        ServiceInstance serviceInstance = loadBalancerClient.choose(Constant.PROVIDER_SERVICE_ID);
        System.out.println("服务地址：" + serviceInstance.getUri());
        System.out.println("服务名称：" + serviceInstance.getServiceId());

        String reqUrl = String.format("http://%s:%s/api/server/users", serviceInstance.getHost(), serviceInstance.getPort());
        LOG.info("请求服务接口地址:{}", reqUrl);

        String response = defaultRestTemplate.getForObject(reqUrl, String.class);
        LOG.info("请求服务接口地址:{} 返回结果:{}", reqUrl, response);
        return response;
    }
}
```
