### ISSUE TITLE
Spring Cloud教程 - 服务自定义元数据

### ISSUE THREAD

**Issue by TFdream** [TFdream/spring-cloud-tutorials#5]
微服务架构下我们通过注册中心实现服务的注册与发现，我们可以在服务注册的时候加上一些元数据信息（分组、版本、机房等）信息来实现一些特殊功能，例如 多IDC部署时同机房优先。

### Eureka
```
eureka:
  instance:
    metadata-map:
      group: green-group 
      version: 1.0
      region: dev
```

### 阿里巴巴Nacos
服务注册配置如下：
```
spring:
  application:
    name: netflix-ribbon-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        metadata:
          "group": green-group
          "version": 1.0
          "region": dev
```
