### ISSUE TITLE
Spring Cloud教程 - Zuul网关入门

### ISSUE THREAD

**Issue by TFdream** [TFdream/spring-cloud-tutorials#7]
Spring Cloud Zuul 是Spring Cloud Netflix 子项目的核心组件之一，可以作为微服务架构中的API网关使用，支持动态路由与过滤功能，本文将对其用法进行详细介绍。

## Zuul简介
API网关为微服务架构中的服务提供了统一的访问入口，客户端通过API网关访问相关服务。API网关的定义类似于设计模式中的门面模式，它相当于整个微服务架构中的门面，所有客户端的访问都通过它来进行路由及过滤。它实现了请求路由、负载均衡、校验过滤、服务容错、服务聚合等功能。

本篇将创建3个服务：
* zuul-proxy：zuul-proxy模块来演示zuul的常用功能；
* user-service：user-service模块来模拟用户服务；
* product-service：product-service模块来模拟商品服务；

本篇中Spring Boot版本为 2.2.4.RELEASE，Spring Cloud版本为Hoxton.SR5。

## 创建zuul-proxy模块

在pom.xml中添加相关依赖：
```
    <properties>
        <spring-cloud.version>Hoxton.SR5</spring-cloud.version>
        <spring-boot.version>2.2.4.RELEASE</spring-boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- 引入 SpringMVC 相关依赖，并实现对其的自动配置 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
        </dependency>
    </dependencies>

```

在application.yml中进行配置：
```
server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

```

在启动类上添加@EnableZuulProxy注解来启用Zuul的API网关功能：
```
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;

/**
 * @author Ricky Fung
 */
@EnableZuulProxy
@EnableDiscoveryClient
@SpringBootApplication
public class ZuulProxyApplication {

    public static void main(String[] args) {
        SpringApplication.run(ZuulProxyApplication.class, args);
    }
}
```

### 启动相关服务
这里我们通过启动eureka-server，两个user-service，product-service和zuul-proxy来演示Zuul的常用功能，启动后注册中心显示如下：
![image](https://user-images.githubusercontent.com/13992911/87746237-a3c10280-c822-11ea-9840-c2ea87e37d98.png)

### 配置路由规则

我们可以通过修改application.yml中的配置来配置路由规则，这里我们将匹配``` /userService/**``` 的请求路由到user-service服务上去，匹配```/productService/**``` 的请求路由到product-service上去，如下：
```
zuul:
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    product-service:
      path: /productService/**
```

验证一下：
* 访问http://localhost:8080/userService/echo/1可以发现请求路由到了user-service上了；
* 访问http://localhost:8080/productService/echo/1可以发现请求路由到了product-service上了。

### 默认路由规则
Zuul和Eureka结合使用，可以实现路由的自动配置，自动配置的路由以服务名称为匹配路径，相当于如下配置：
```
zuul:
  routes: #给服务配置路由
    user-service:
      path: /user-service/**
    product-service:
      path: /product-service/**
```

验证一下：
* 访问http://localhost:8080/user-service/echo/1 可以发现请求路由到了user-service上了；
* 访问http://localhost:8080/product-service/echo/1 可以发现请求路由到了product-service上了。

如果不想使用默认的路由规则，可以添加以下配置来忽略默认路由配置：
```
zuul:
  ignored-services: user-service,product-service #关闭默认路由配置
```

## 相关资料
* [Spring Cloud Zuul：API网关服务](https://juejin.im/post/5d9f2dea6fb9a04e3e724067)
